# @name Signup
POST {{baseUrl}}/signup
Content-Type: application/json

{}

###

# @name Post Report
POST {{baseUrl}}/report
Content-Type: application/json

{
  "resource_captures": [
    {
      "type": "HashiCorp Vault Service",
      "id": "vault.demo.chase.dev.servicearch.com",
      "first_seen_at": "2024-10-11T00:25:15.078987097Z",
      "last_seen_at": "2024-10-11T00:25:15.128806257Z",
      "contains": [
        {
          "type": "Secrets Engine Mount",
          "id": "secret",
          "first_seen_at": "2024-10-11T00:25:15.078885557Z",
          "last_seen_at": "2024-10-11T00:25:15.128675262Z",
          "contains": [
            {
              "type": "Secret",
              "id": "stg/sprockets/db_creds",
              "first_seen_at": "2024-10-11T00:25:15.078752919Z",
              "last_seen_at": "2024-10-11T00:25:15.078752919Z"
            },
            {
              "type": "Secret",
              "id": "prod/sprockets/db_creds",
              "first_seen_at": "2024-10-11T00:25:15.128522998Z",
              "last_seen_at": "2024-10-11T00:25:15.128522998Z"
            }
          ]
        }
      ]
    },
    {
      "type": "GitHub Service",
      "id": "https://github.com",
      "first_seen_at": "2024-10-11T00:24:54.216929402Z",
      "last_seen_at": "2024-10-11T00:24:54.216929402Z",
      "contains": [
        {
          "type": "Organization",
          "id": "txase",
          "first_seen_at": "2024-10-11T00:24:54.216669556Z",
          "last_seen_at": "2024-10-11T00:24:54.216669556Z",
          "contains": [
            {
              "type": "Git Repository",
              "id": "txase/archodex-demo-sprockets",
              "first_seen_at": "2024-10-11T00:24:54.216581932Z",
              "last_seen_at": "2024-10-11T00:24:54.216581932Z",
              "contains": [
                {
                  "type": "GitHub Actions Workflow",
                  "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main",
                  "first_seen_at": "2024-10-11T00:24:54.216488328Z",
                  "last_seen_at": "2024-10-11T00:24:54.216488328Z"
                }
              ]
            }
          ]
        },
        {
          "type": "Actor",
          "id": "txase",
          "first_seen_at": "2024-10-11T00:24:54.216756679Z",
          "last_seen_at": "2024-10-11T00:24:54.216756679Z"
        },
        {
          "type": "Actor",
          "id": "txase",
          "first_seen_at": "2024-10-11T00:24:54.216843311Z",
          "last_seen_at": "2024-10-11T00:24:54.216843311Z"
        }
      ]
    },
    {
      "type": "HTTPS Server",
      "id": "terraform-states-891376912002.s3.us-west-2.amazonaws.com",
      "first_seen_at": "2024-10-11T00:25:00.823699558Z",
      "last_seen_at": "2024-10-11T00:25:11.165449195Z",
      "contains": [
        {
          "type": "Route",
          "id": "/",
          "first_seen_at": "2024-10-11T00:25:00.823507289Z",
          "last_seen_at": "2024-10-11T00:25:10.579242187Z"
        },
        {
          "type": "Route",
          "id": "/demo-sprockets/terraform.tfstate",
          "first_seen_at": "2024-10-11T00:25:01.239777398Z",
          "last_seen_at": "2024-10-11T00:25:11.165269269Z"
        }
      ]
    }
  ],
  "event_captures": [
    {
      "principals": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Actor",
            "id": "txase"
          }
        ]
      ],
      "resources": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Actor",
            "id": "txase"
          }
        ]
      ],
      "events": [
        {
          "type": "Assumed",
          "first_seen_at": "2024-10-11T00:24:54.217198545Z",
          "last_seen_at": "2024-10-11T00:24:54.217198545Z"
        }
      ]
    },
    {
      "principals": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Organization",
            "id": "txase"
          },
          {
            "type": "Git Repository",
            "id": "txase/archodex-demo-sprockets"
          },
          {
            "type": "GitHub Actions Workflow",
            "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
          }
        ]
      ],
      "resources": [
        [
          {
            "type": "HashiCorp Vault Service",
            "id": "vault.demo.chase.dev.servicearch.com"
          },
          {
            "type": "Secrets Engine Mount",
            "id": "secret"
          },
          {
            "type": "Secret",
            "id": "stg/sprockets/db_creds"
          }
        ]
      ],
      "events": [
        {
          "type": "Read",
          "first_seen_at": "2024-10-11T00:25:15.079090911Z",
          "last_seen_at": "2024-10-11T00:25:15.079090911Z"
        }
      ]
    },
    {
      "principals": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Organization",
            "id": "txase"
          },
          {
            "type": "Git Repository",
            "id": "txase/archodex-demo-sprockets"
          },
          {
            "type": "GitHub Actions Workflow",
            "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
          }
        ]
      ],
      "resources": [
        [
          {
            "type": "HashiCorp Vault Service",
            "id": "vault.demo.chase.dev.servicearch.com"
          },
          {
            "type": "Secrets Engine Mount",
            "id": "secret"
          },
          {
            "type": "Secret",
            "id": "prod/sprockets/db_creds"
          }
        ]
      ],
      "events": [
        {
          "type": "Read",
          "first_seen_at": "2024-10-11T00:25:15.128919489Z",
          "last_seen_at": "2024-10-11T00:25:15.128919489Z"
        }
      ]
    },
    {
      "principals": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Organization",
            "id": "txase"
          },
          {
            "type": "Git Repository",
            "id": "txase/archodex-demo-sprockets"
          },
          {
            "type": "GitHub Actions Workflow",
            "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
          }
        ]
      ],
      "resources": [
        [
          {
            "type": "HTTPS Server",
            "id": "terraform-states-891376912002.s3.us-west-2.amazonaws.com"
          },
          {
            "type": "Route",
            "id": "/"
          }
        ]
      ],
      "events": [
        {
          "type": "Read",
          "first_seen_at": "2024-10-11T00:25:00.823841003Z",
          "last_seen_at": "2024-10-11T00:25:10.579459744Z"
        }
      ]
    },
    {
      "principals": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Organization",
            "id": "txase"
          },
          {
            "type": "Git Repository",
            "id": "txase/archodex-demo-sprockets"
          },
          {
            "type": "GitHub Actions Workflow",
            "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
          }
        ]
      ],
      "resources": [
        [
          {
            "type": "HTTPS Server",
            "id": "terraform-states-891376912002.s3.us-west-2.amazonaws.com"
          },
          {
            "type": "Route",
            "id": "/demo-sprockets/terraform.tfstate"
          }
        ]
      ],
      "events": [
        {
          "type": "Read",
          "first_seen_at": "2024-10-11T00:25:01.240045940Z",
          "last_seen_at": "2024-10-11T00:25:11.165609465Z"
        }
      ]
    },
    {
      "principals": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Actor",
            "id": "txase"
          }
        ]
      ],
      "resources": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Organization",
            "id": "txase"
          },
          {
            "type": "Git Repository",
            "id": "txase/archodex-demo-sprockets"
          },
          {
            "type": "GitHub Actions Workflow",
            "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
          }
        ]
      ],
      "events": [
        {
          "type": "Invoked",
          "first_seen_at": "2024-10-11T00:24:54.217587372Z",
          "last_seen_at": "2024-10-11T00:24:54.217587372Z"
        }
      ]
    }
  ]
}

###

# @name Query all entities
GET {{baseUrl}}/query
Content-Type: application/json

{
  "type": "ALL"
}