# @name Create account
POST {{baseUrl}}/accounts
Content-Type: application/json

{}

###

# @name List accounts
GET {{baseUrl}}/accounts

###

# @name Post Report
POST {{baseUrl}}/report
Content-Type: application/json
Authorization: {{report_api_key}}

{
  "resource_captures": [
    {
      "type": "GitHub Service",
      "id": "https://github.com",
      "first_seen_at": "2024-10-18T22:05:11.217686330Z",
      "last_seen_at": "2024-10-18T22:05:11.217686330Z",
      "contains": [
        {
          "type": "Organization",
          "id": "txase",
          "first_seen_at": "2024-10-18T22:05:11.217439265Z",
          "last_seen_at": "2024-10-18T22:05:11.217439265Z",
          "contains": [
            {
              "type": "Git Repository",
              "id": "txase/archodex-demo-sprockets",
              "first_seen_at": "2024-10-18T22:05:11.217352602Z",
              "last_seen_at": "2024-10-18T22:05:11.217352602Z",
              "contains": [
                {
                  "type": "GitHub Actions Workflow",
                  "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main",
                  "first_seen_at": "2024-10-18T22:05:11.217263724Z",
                  "last_seen_at": "2024-10-18T22:05:11.217263724Z"
                }
              ]
            }
          ]
        },
        {
          "type": "Actor",
          "id": "txase",
          "first_seen_at": "2024-10-18T22:05:11.217522552Z",
          "last_seen_at": "2024-10-18T22:05:11.217522552Z"
        },
        {
          "type": "Actor",
          "id": "txase",
          "first_seen_at": "2024-10-18T22:05:11.217605558Z",
          "last_seen_at": "2024-10-18T22:05:11.217605558Z"
        }
      ]
    },
    {
      "type": "HTTPS Server",
      "id": "terraform-states-891376912002.s3.us-west-2.amazonaws.com",
      "first_seen_at": "2024-10-18T22:05:17.768077384Z",
      "last_seen_at": "2024-10-18T22:05:27.325594761Z",
      "contains": [
        {
          "type": "Route",
          "id": "/",
          "first_seen_at": "2024-10-18T22:05:17.767926110Z",
          "last_seen_at": "2024-10-18T22:05:27.071775594Z"
        },
        {
          "type": "Route",
          "id": "/demo-sprockets/terraform.tfstate",
          "first_seen_at": "2024-10-18T22:05:17.981697927Z",
          "last_seen_at": "2024-10-18T22:05:27.325453484Z"
        }
      ]
    },
    {
      "type": "HashiCorp Vault Service",
      "id": "vault.demo.chase.dev.servicearch.com",
      "first_seen_at": "2024-10-18T22:05:29.891267230Z",
      "last_seen_at": "2024-10-18T22:05:29.899106681Z",
      "contains": [
        {
          "type": "Secrets Engine Mount",
          "id": "secret",
          "first_seen_at": "2024-10-18T22:05:29.891168745Z",
          "last_seen_at": "2024-10-18T22:05:29.899006042Z",
          "contains": [
            {
              "type": "Secret",
              "id": "prod/sprockets/db_creds",
              "first_seen_at": "2024-10-18T22:05:29.891033451Z",
              "last_seen_at": "2024-10-18T22:05:29.891033451Z"
            },
            {
              "type": "Secret",
              "id": "qa/sprockets/db_creds",
              "first_seen_at": "2024-10-18T22:05:29.898896025Z",
              "last_seen_at": "2024-10-18T22:05:29.898896025Z"
            }
          ]
        }
      ]
    }
  ],
  "event_captures": [
    {
      "principals": [
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ]
        }
      ],
      "resources": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Actor",
            "id": "txase"
          }
        ]
      ],
      "events": [
        {
          "type": "Assumed",
          "first_seen_at": "2024-10-18T22:05:11.218919811Z",
          "last_seen_at": "2024-10-18T22:05:11.218919811Z"
        }
      ]
    },
    {
      "principals": [
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ],
          "event": "Assumed"
        },
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ],
          "event": "Invoked"
        },
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Organization",
              "id": "txase"
            },
            {
              "type": "Git Repository",
              "id": "txase/archodex-demo-sprockets"
            },
            {
              "type": "GitHub Actions Workflow",
              "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
            }
          ]
        }
      ],
      "resources": [
        [
          {
            "type": "HTTPS Server",
            "id": "terraform-states-891376912002.s3.us-west-2.amazonaws.com"
          },
          {
            "type": "Route",
            "id": "/"
          }
        ]
      ],
      "events": [
        {
          "type": "Read",
          "first_seen_at": "2024-10-18T22:05:17.768187380Z",
          "last_seen_at": "2024-10-18T22:05:27.072064741Z"
        }
      ]
    },
    {
      "principals": [
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ],
          "event": "Assumed"
        },
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ],
          "event": "Invoked"
        },
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Organization",
              "id": "txase"
            },
            {
              "type": "Git Repository",
              "id": "txase/archodex-demo-sprockets"
            },
            {
              "type": "GitHub Actions Workflow",
              "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
            }
          ]
        }
      ],
      "resources": [
        [
          {
            "type": "HashiCorp Vault Service",
            "id": "vault.demo.chase.dev.servicearch.com"
          },
          {
            "type": "Secrets Engine Mount",
            "id": "secret"
          },
          {
            "type": "Secret",
            "id": "prod/sprockets/db_creds"
          }
        ]
      ],
      "events": [
        {
          "type": "Read",
          "first_seen_at": "2024-10-18T22:05:29.891371286Z",
          "last_seen_at": "2024-10-18T22:05:29.891371286Z"
        }
      ]
    },
    {
      "principals": [
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ],
          "event": "Assumed"
        },
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ],
          "event": "Invoked"
        },
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Organization",
              "id": "txase"
            },
            {
              "type": "Git Repository",
              "id": "txase/archodex-demo-sprockets"
            },
            {
              "type": "GitHub Actions Workflow",
              "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
            }
          ]
        }
      ],
      "resources": [
        [
          {
            "type": "HashiCorp Vault Service",
            "id": "vault.demo.chase.dev.servicearch.com"
          },
          {
            "type": "Secrets Engine Mount",
            "id": "secret"
          },
          {
            "type": "Secret",
            "id": "qa/sprockets/db_creds"
          }
        ]
      ],
      "events": [
        {
          "type": "Read",
          "first_seen_at": "2024-10-18T22:05:29.899206088Z",
          "last_seen_at": "2024-10-18T22:05:29.899206088Z"
        }
      ]
    },
    {
      "principals": [
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ],
          "event": "Assumed"
        },
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ]
        }
      ],
      "resources": [
        [
          {
            "type": "GitHub Service",
            "id": "https://github.com"
          },
          {
            "type": "Organization",
            "id": "txase"
          },
          {
            "type": "Git Repository",
            "id": "txase/archodex-demo-sprockets"
          },
          {
            "type": "GitHub Actions Workflow",
            "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
          }
        ]
      ],
      "events": [
        {
          "type": "Invoked",
          "first_seen_at": "2024-10-18T22:05:11.219566208Z",
          "last_seen_at": "2024-10-18T22:05:11.219566208Z"
        }
      ]
    },
    {
      "principals": [
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ],
          "event": "Assumed"
        },
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Actor",
              "id": "txase"
            }
          ],
          "event": "Invoked"
        },
        {
          "id": [
            {
              "type": "GitHub Service",
              "id": "https://github.com"
            },
            {
              "type": "Organization",
              "id": "txase"
            },
            {
              "type": "Git Repository",
              "id": "txase/archodex-demo-sprockets"
            },
            {
              "type": "GitHub Actions Workflow",
              "id": "txase/archodex-demo-sprockets/.github/workflows/deploy.yml@refs/heads/main"
            }
          ]
        }
      ],
      "resources": [
        [
          {
            "type": "HTTPS Server",
            "id": "terraform-states-891376912002.s3.us-west-2.amazonaws.com"
          },
          {
            "type": "Route",
            "id": "/demo-sprockets/terraform.tfstate"
          }
        ]
      ],
      "events": [
        {
          "type": "Read",
          "first_seen_at": "2024-10-18T22:05:17.982042053Z",
          "last_seen_at": "2024-10-18T22:05:27.325711682Z"
        }
      ]
    }
  ]
}

###

# @name Query all entities
GET {{baseUrl}}/query/all