name: Cargo Clippy and Format Checks

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup package repos
        run: |-
          sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
          path-exclude /usr/share/doc/*
          path-exclude /usr/share/man/*
          path-exclude /usr/share/info/*
          EOF

          sudo apt-get update

      - name: Install development tools
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: mold protobuf-compiler

      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy,rustfmt

      - name: Cargo Clippy Check
        run:
          cargo clippy --workspace --keep-going --all-targets --exclude archodex-com --no-default-features -- --deny
          clippy::pedantic

      - name: Cargo Format Check
        # cargo fmt doesn't have an --exclude or similar argument to exclude the archodex-com package, so we have to
        # list all other packages to check instead of using --all
        run:
          cargo fmt --check --package archodex-backend --package archodex-error --package lambda --package migrator
          --package server

      - uses: actions/setup-node@v4

      - run: npx prettier --check .
