apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archodex-backend-dev
  labels:
    app: archodex-backend-dev
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 100Gi
