apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archodex-backend-dev-dynamodb-local
  labels:
    app: archodex-backend-dev
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
